server:
  port: 3000

db:
  type: 'postgres'
  database: 'postgres'
  host: 'margdarsandev.c9zchczwypcl.ap-south-1.rds.amazonaws.com'
  port: 5432
  username: 'postgres'
  password: 'postgres'
  synchronize: false
#  type: 'postgres'
#  database: 'new'
#  host: 'pg.c9zchczwypcl.ap-south-1.rds.amazonaws.com'
#  port: 5432
#  username: 'pg'
#  password: '1234567890'
#  #  change to false in production
#  synchronize: false

jwt:
  secret: 'jfal24dfaee324'
#  expiresIn: 3600

razorpay:
#  keyId: 'rzp_live_EwED1ul2Uv65Rt'
#  keySecret: 'zR7ogR4hmkJVtKEC5mrcuvWk'
#  webhookSecret: 'sfjfd$jl@*%KJLHFE#$@@$'
  keyId: 'rzp_test_RUpmgSgMUlsx94'
  keySecret: 'nGzDAwYxGrrdsT6JOAnFT9LY'
  webhookSecret: 'sahdklH#@$LCDA$#&SLJ!#@RH!K@'